### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by johanguse** [RicardoGEsteves/omniscient#247]
Hey Ricardo, would you happen to have a working demo to show your boilerplate functions ? Is it possible for you to host it on Vercel? I really like to use but I need to check it before try.

Thanks!

**Comment by RicardoGEsteves** [comment]
> Hey Ricardo, would you happen to have a working demo to show your boilerplate functions ? Is it possible for you to host it on Vercel? I really like to use but I need to check it before try.
> 
> Thanks!

Hello @johanguse, thank you for your message and for liking my project.
It's not live anymore, I needed to remove the database to have space to create new ones, and new projects.
Also if you want to use it you have to implement some small changes on the config files but it's something really straight forward.
I would recommend you to clone or fork the project create a dummy db and test if what you looking for.
